services:
  db:
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_USER: emt
      POSTGRES_PASSWORD: emt
      POSTGRES_DB: accommodations
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  pgdata: