spring.application.name=emt-lab-group-b

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

spring.profiles.active=dev

# Task 6: Interval for refreshing the category_stats materialized view (10 minutes)
app.materialized-view.refresh-interval-ms=600000
