spring.datasource.url=jdbc:postgresql://localhost:5433/accommodations
spring.datasource.username=emt
spring.datasource.password=emt

spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE